# Generated by Django 4.0.5 on 2022-06-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
